shape: sequence_diagram
Scientific: { shape: circle }
External: { shape: diamond }
Editorial: { shape: diamond }
Scientific.t1 -> External.t1: "Start Experiment"
External.t1."Computational Experiment"
Scientific.t1 -> External.t1: "Checkpoint"
External.t1 -> Editorial.t1: "Data Transfer"
Editorial."Direct Reproducibility"
Editorial.t1 -> Scientific.t1: "End Experiment"




